# Model Configurations
goal_dim: 32
horizon: 16
max_interval: 16
n_critics: 5
rl_coeff: 0.05
kl_coeff: 0
decoder_coeff: 0
diffuser_coeff: 0.001
predict_epsilon: True
diffuser_timesteps: 20
sample_timesteps: 300
returns_condition: False
goal_condition: True
condition_guidance_w: 0.5
hidden_size: 512
model_type: 'diffusion' # 'diffusion' or 'flowmatching'

# Training Configurations
batch_size: 32
learning_rate: 0.0001
warmup_updates: 50000
updates_per_epoch: 10000
epochs: 100

# Evaluation Configurations
threshold: 0.1
time_limit: 10
